sample_survey/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls'))
]

survey/urls.py
"""Routing for survey application

This file consists of URL routes for the survey application.
The application is a Single Page Application(SPA) with 5 views.

About:
-----
About page briefly explains the goal and features of the project.

Surveys:
--------
This page lists all the available surveys created by the admin.
Each survey can be interacted with and on click routes to survey details page.

Survey Details:
---------------
This page renders a form with the questionnaire for the survey.
Each question has atleast two choices and are radio inputs.

Survey Submit Success:
----------------------
This is the success landing page for successful submission of the survey.
"""

from django.urls import path
from . import views

urlpatterns = [
    # Default path is /survey/ which invokes index view without any params
    path('', views.index, name="index"),

    # API GET endpoint for returning popular survey among existing surveys.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_popular_survey/', views.get_popular_survey, name="get_popular_survey"),

    # API GET endpoint for returning survey objects along with corresponding questions and choices.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_all_surveys/', views.get_all_surveys, name="get_all_surveys"),

    # This is the view hook to submit survey form,
    # update entities based on the submitted form and redirect to success page
    path('submit_survey/', views.submit_survey, name="submit_survey"),

    # This is the generic route for rendering all partial views without params
    # All routes are intercepted by index view middleware and respective partial view will be rendered accordingly
    # Note: This is a work around as at this point I could not find a better solution
    # or documentation to create partial views
    path('<str:partial_view>/', views.index, name="index/partial_view"),

    # This is the generic route for rendering partial views with id parameter
    path('<str:partial_view>/<int:pk>', views.index, name="index/partial_view/id"),
]

survey/models.py
"""Python Database API

Django DB Models can be used to create schemas for database entities
which will then be used to create the physical database.

Models:
-------
Survey:
Survey entity encapsulates basic attributes of a survey including
name(survey name) and published_on(date time when the survey is published.
Methods:
    __str__: returns the survey name as metadata reference when objects are accessed.
    was_published_recently: returns True if the survey was published in the last 24h.
                            The callback is also used by the admin for filtering surveys.

Participant:
This entity helps keep track of number of successful survey submits. This entity is used
to identify the popular survey i.e., the survey with most submissions.
The attributes include survey(foreign key referencing Survey) and participation_datetime.
Methods:
    __str__: returns the Participant name as metadata reference when objects are accessed.

Question:
This entity encapsulates a question in the survey with survey(foreign key referencing Survey),
question_text(actual question text) and created_on.
Methods:
    __str__: returns the Question name as metadata reference when objects are accessed.

Choice:
This entity encapsulates a choice attribute in the survey with Question(foreign key referencing Question),
choice_text(actual choice text), votes(to store poll results) and created_on.
Methods:
    __str__: returns the Choice name as metadata reference when objects are accessed.

"""

from django.db import models
from django.utils import timezone
import datetime


class Survey(models.Model):
    """Class to encapsulate Survey entity
    Attributes:
        name: character field with max_length=200
        published_on: datetime field

    """
    name = models.CharField(max_length=200)
    published_on = models.DateTimeField('Published DateTime')

    def __str__(self):
        return self.name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_on <= now

    was_published_recently.admin_order_field = 'published_on'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Participant(models.Model):
    """Class to encapsulate Participant entity
    Attributes:
        survey: foreign key to Survey
        participation_datetime: datetime field

    """
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    participation_datetime = models.DateTimeField('Participation DateTime')

    def __str__(self):
        return "Participant "+str(self.participation_datetime)


class Question(models.Model):
    """Class to encapsulate Participant entity
    Attributes:
        survey: foreign key to Survey
        question_text: character field with max_length=200
        created_on: datetime field

    """
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('Creation DateTime')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    """Class to encapsulate Participant entity
    Attributes:
        survey: foreign key to Question
        choice_text: character field with max_length=200
        created_on: datetime field
        votes: number with default 0

    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('Creation DateTime')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

survey/views.py
"""Create Views for the application

Here you can create views for the survey application.
Each view will be either mapped directly to a URL in the routing
or will be used to render partial views using inclusion_tags.

index:
------
This is the default view for the start site of the application.
Also, this is a middleware for routing requests to partial views.
all_partial_views: is a list of partial views that are registered with index.
Default partial view is 'about'.

all_surveys:
------------
This is the partial view rendering list of surveys created by the admin.
Context object is currently not being used.
However, it is a required param for invoking the view from inclusion template tag.

about:
------
This is the partial view for rendering about page. The view only displays static content.

survey_details:
---------------
This is the partial view for the survey form. It accepts survey id as querystring parameter.
It provides survey details for the survey id provided for the html template.

submit_success:
---------------
This is the partial view for displaying submit success message.

submit_survey:
--------------
This is the hook for form submit which gets the voted choices.
From this it increments the votes of respective choices.
Also, it creates a participant instance tracking the survey participation
and the datetime at which the survey was taken.

get_popular_survey:
-------------------
This is the API GET endpoint for returning popular survey among existing surveys.
This endpoint can also be used as a web hook in future. Currently it is used within the application.

get_all_surveys:
----------------
API GET endpoint for returning survey objects along with corresponding questions and choices.
This endpoint can also be used as a web hook in future. Currently it is used within the application.

"""

from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.template.loader_tags import register
from django.views.decorators.http import require_http_methods
from .models import Survey, Question, Choice, Participant
from django.utils import timezone
from django.core import serializers
import operator

all_partial_views = ['about', 'all_surveys', 'survey_details', 'submit_success']


@require_http_methods(["GET"])
def index(request, partial_view=None, pk=None):
    if partial_view is None:
        partial_view = 'about'
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})
    elif all_partial_views.count(partial_view) == 0:
        raise Http404('Partial View not found!')
    elif partial_view == "survey_details" and pk is None:
        raise Http404('Invalid Address! Page Not Found')
    else:
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})


@register.inclusion_tag('survey/surveys.html', takes_context=True)
def all_surveys(context):
    surveys = Survey.objects.all()
    return {'surveys': surveys}


@register.inclusion_tag('survey/about.html', takes_context=True)
def about(context):
    return {}


@register.inclusion_tag('survey/survey_details.html', takes_context=True)
def survey_details(context, survey_id):
    survey = Survey.objects.get(id=survey_id)
    return {'survey': survey}


@register.inclusion_tag('survey/submit_success.html', takes_context=True)
def submit_success(context):
    return {}


@require_http_methods(["POST"])
def submit_survey(request):
    form_data = request.POST.copy()
    # Example: {'csrfmiddlewaretoken': ['idT13LGpggg78Yr0rU3vSkT1PQxnM9hT7z97FvuZEBb
    # IU2acygAUr2W3FE9SCGbk'], '1': ['choice/3'], '2': ['choice/5']}
    form_items = list(form_data.items())
    print("form_items", form_items)
    form_items.pop(0)  # the first element is the csrf token. Therefore omit it.
    survey = None
    for item in form_items:
        # Here in 'choice/3', '3' is '<choice_id>'.
        choice_str, choice_id = item
        choice_id = int(choice_id.split('/')[1])
        choice = Choice.objects.get(id=choice_id)
        if survey is None:
            survey = choice.question.survey
        choice.votes = choice.votes + 1
        choice.save()
    if survey is not None:
        participant = Participant(survey=survey, participation_datetime=timezone.now())
        participant.save()
    return redirect('/survey/submit_success/')


@require_http_methods(["GET"])
def get_popular_survey(request):
    popular_survey_id = None
    popular_survey = None
    surveys = Survey.objects.all()
    survey_participants_dict = {}
    for survey in surveys:
        num_participants = Participant.objects.filter(survey=survey).count()
        survey_participants_dict[survey.id] = num_participants
    if len(survey_participants_dict) > 0:
        popular_survey_id = max(survey_participants_dict.items(), key=operator.itemgetter(1))[0]
    if popular_survey_id is not None:
        popular_survey = serializers.serialize("json", surveys.filter(id=popular_survey_id))
    return JsonResponse(popular_survey, safe=False)


@require_http_methods(["GET"])
def get_all_surveys(request):
    surveys = Survey.objects.all()
    questions = Question.objects.all()
    choices = Choice.objects.all()

    return JsonResponse({"surveys": serializers.serialize("json", surveys),
                         "questions": serializers.serialize("json", questions),
                         "choices": serializers.serialize("json", choices)})

survey/templates/survey/about.html
<div class="card">
  {% load static %}
  <img class="card-img-top survey-about-img" src="{% static 'img/about.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">About This App</h5>
    <p class="card-text">This is a survey application created using
      <a href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/" target="_blank">django framework</a>.
      In this app, users can participate in surveys created by the administrator.
      Each survey consists of a short questionnaire. At the same time fun.
      Each participation in the survey is recorded and the admin can track the number of participation for each survey
      and will be notified of the top survey with highest participation.
      Also, can see the stats for each question in a survey with bar chart visualizations rendered using
      <a href="https://www.chartjs.org/" target="_blank">Chartjs</a>.</p>
  </div>
</div>

survey/templates/survey/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/survey-app.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Sample Survey Application</title>
</head>
{% load static %}
<body style="background-image: url('{% static 'img/background.jpg' %}')">
    <nav class="navbar navbar-expand-lg dark" style="background-color: #333;">
      <a class="navbar-brand survey-navbar-link" href="#">Sample Survey Application</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if partial_view == "about" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/survey/about/">About <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/survey/about/">About</a>
                </li>
            {% endif %}
            {% if partial_view == "all_surveys" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/survey/all_surveys/">Surveys <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/survey/all_surveys/">Surveys</a>
                </li>
            {% endif %}
            <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/admin/">Admin Page</a>
            </li>

<!--          <li class="nav-item dropdown">-->
<!--            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--              Dropdown-->
<!--            </a>-->
<!--            <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--              <a class="dropdown-item" href="#">Action</a>-->
<!--              <a class="dropdown-item" href="#">Another action</a>-->
<!--              <div class="dropdown-divider"></div>-->
<!--              <a class="dropdown-item" href="#">Something else here</a>-->
<!--            </div>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link disabled" href="#">Disabled</a>-->
<!--          </li>-->
        </ul>
<!--        <form class="form-inline my-2 my-lg-0">-->
<!--          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--        </form>-->
      </div>
    </nav>
        {% if partial_view == 'about' %}
            {% about %}
        {% endif %}
        {% if partial_view == 'all_surveys' %}
            {% all_surveys %}
        {% endif %}
        {% if partial_view == 'survey_details' %}
            {% survey_details pk %}
        {% endif %}
        {% if partial_view == 'submit_success' %}
            {% submit_success %}
        {% endif %}

</body>
</html>

survey/templates/survey/submit_success.html
<div class="card">
  {% load static %}
  <img class="card-img-top survey-about-img" src="{% static 'img/thank-you.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <p class="card-text">Thank you for taking part in the survey. We whole heartedly appreciate it.</p>
    <a href="/survey/all_surveys" class="btn btn-primary">Take Another Survey</a>
  </div>
</div>

survey/templates/survey/survey_details.html
<div class="card survey-form-card">
  <h5 class="card-header">{{survey.name}}</h5>
  <div class="card-body">
      <p class="card-text">Kindly fill in the survey and submit to participate</p>
      <form action="/survey/submit_survey/" method="post">
      {% csrf_token %}
      {% for question in survey.question_set.all %}
          <fieldset class="form-group">
            <div class="row">
              <legend class="col-form-label col-md-6 pt-0">{{question.question_text}}</legend>
              <div class="col-md-6">
                {% for choice in question.choice_set.all %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="{{question.id}}"
                             id="{{question.id}}{{choice.id}}" value="choice/{{choice.id}}" aria-describedby="radioHelp">
                      <label class="form-check-label" for="{{question.id}}{{choice.id}}">
                        {{choice.choice_text}}
                      </label>
                    </div>
                {% endfor %}
                <small id="radioHelp" class="form-text text-muted">Please select one of the available choices.</small>
              </div>
            </div>
          </fieldset>
          <hr/>
      {% endfor %}
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>
  </div>
</div>

survey/templates/survey/surveys.html
<div class="card">
  <h5 class="card-header">Available Surveys</h5>
  <div class="card-body">
      <p class="card-text">Participate in as many surveys as you like and help us understand you better!</p>
      <ul>
        {% for survey in surveys %}
            <li>
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title"><a href="/survey/survey_details/{{survey.id}}">{{survey.name}}</a></h5>
                  </div>
                </div>
            </li>
        {% endfor %}
      </ul>
  </div>
</div>